### ISSUE TITLE
Memory Leaking issues

### ISSUE THREAD

**Issue by OGarland001** [tylerscheifley/Ford-Assembly-Plant-Sec-2-Group-1#11]
![image](https://user-images.githubusercontent.com/90342911/204380412-63d061e9-ffe8-48b1-8a17-ad4560c14a0d.png)

The memory stays consistently increasing for the lower values but as the it gets past 70% it seems to increase quite a lot till working on managing our memory with the import of imGui

**Comment by BroCoRo** [comment]
![image](https://user-images.githubusercontent.com/85836332/205220259-6719f01e-f8b3-4fa7-b5ce-b637ac4a279b.png)

It looks like its the constant loading of the images that is causing the memory problem as if I comment out all lines that load the images, the memory stays stable at 30mb of memory usage through the whole program (I went to around 30 vehicles made with no increase in RAM usage at all). I think we should look into the loading of the images and seeing if we can mange the image memory/freeing (this might mean we have to use a different image loading method).

**Comment by OGarland001** [comment]
https://github.com/tylerscheifley/Ford-Assembly-Plant-Sec-2-Group-1/commit/d97d4713f36f4da56bbe8f9b5e083db138366a7d


add a commit to free image textures every time it loops, realized that It wasn't truly only Imgui, OpenGl Was holding onto the allocations for the interface.
